// 初期テスト用静的データ、基本的に不使用
import { WorkoutType, MasterItemType, MuscleType } from './types';

export const workoutGroup: WorkoutType[] = [
  {
    id: 1,
    name: '自重',
  },
  {
    id: 2,
    name: 'フリーウェイト',
  },
  {
    id: 3,
    name: 'マシン',
  },
  {
    id: 4,
    name: '有酸素運動',
  },
];

export const MuscleList: MuscleType[] = [
  {
    id: 1,
    part: '胸',
    name: '大胸筋',
  },
  {
    id: 2,
    part: '背中',
    name: '僧帽筋',
  },
  {
    id: 3,
    part: '背中',
    name: '大円筋',
  },
  {
    id: 4,
    part: '背中',
    name: '広背筋',
  },
  {
    id: 5,
    part: '背中',
    name: '脊柱起立筋',
  },
  {
    id: 6,
    part: '背中',
    name: '腰筋',
  },
  {
    id: 7,
    part: '肩',
    name: '棘上筋',
  },
  {
    id: 8,
    part: '肩',
    name: '三角筋',
  },
  {
    id: 9,
    part: '腕',
    name: '上腕二頭筋',
  },
  {
    id: 10,
    part: '腕',
    name: '上腕三頭筋',
  },
  {
    id: 11,
    part: '足',
    name: '大殿筋',
  },
  {
    id: 12,
    part: '足',
    name: '大腿四頭筋',
  },
  {
    id: 13,
    part: '足',
    name: 'ハムストリングス',
  },
  {
    id: 14,
    part: '足',
    name: '内腿広筋',
  },
  {
    id: 15,
    part: '足',
    name: '外腿広筋',
  },
  {
    id: 16,
    part: '足',
    name: '腓腹筋',
  },
  {
    id: 17,
    part: '腹',
    name: '腹筋',
  },
];

export const MasterListData: MasterItemType[] = [
  {
    id: 1,
    name: '腕立て伏せ',
    image: '/images/body_weight.png',
    type: 1,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 2,
    name: 'ディップス',
    image: '/images/chinning_dips.png',
    type: 1,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 3,
    name: 'ベンチプレス',
    image: '/images/brench_press.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10, 12, 13],
  },
  {
    id: 4,
    name: 'インクラインベンチプレス',
    image: '/images/brench_press.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10, 12, 13],
  },
  {
    id: 5,
    name: 'デクラインベンチプレス',
    image: '/images/brench_press.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10, 12, 13],
  },
  {
    id: 6,
    name: 'ダンベルプレス',
    image: '/images/dumbbell.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 7,
    name: 'インクラインダンベルプレス',
    image: '/images/dumbbell.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 8,
    name: 'デクラインダンベルプレス',
    image: '/images/dumbbell.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 9,
    name: 'ダンベルフライ',
    image: '/images/dumbbell.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 10,
    name: 'インクラインダンベルフライ',
    image: '/images/dumbbell.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 11,
    name: 'デクラインダンベルフライ',
    image: '/images/dumbbell.png',
    type: 2,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 12,
    name: 'ペイクフライ',
    image: '/images/rear_delt_fly.png',
    type: 3,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 13,
    name: 'ケーブルクロスオーバー',
    image: '/images/cable_machine.png',
    type: 3,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 14,
    name: 'チェストプレス',
    image: '/images/chest_press.png',
    type: 3,
    target: 1,
    muscles: [1, 8, 10],
  },
  {
    id: 15,
    name: 'スミスベンチプレス',
    image: '/images/smith_machine.png',
    type: 3,
    target: 1,
    muscles: [1, 8, 10, 12, 13],
  },
  {
    id: 16,
    name: 'インクラインスミスベンチプレス',
    image: '/images/smith_machine.png',
    type: 3,
    target: 1,
    muscles: [1, 8, 10, 12, 13],
  },
  {
    id: 17,
    name: 'デクラインスミスベンチプレス',
    image: '/images/smith_machine.png',
    type: 3,
    target: 1,
    muscles: [1, 8, 10, 12, 13],
  },
  {
    id: 18,
    name: 'チンニング',
    image: '/images/chinning_dips.png',
    type: 1,
    target: 4,
    muscles: [2, 3, 4, 5, 9],
  },
  {
    id: 19,
    name: 'ベントオーバーロー',
    image: '/images/power_rack.png',
    type: 2,
    target: 4,
    muscles: [2, 3, 4, 5, 9],
  },
  {
    id: 20,
    name: 'ワンハンドローイング',
    image: '/images/brench.png',
    type: 2,
    target: 4,
    muscles: [2, 3, 4, 5, 9],
  },
  {
    id: 21,
    name: 'ラットプルダウン',
    image: '/images/lat_pulldown.png',
    type: 3,
    target: 4,
    muscles: [2, 3, 4, 5, 9],
  },
  {
    id: 22,
    name: 'シーテッドローイング',
    image: '/images/seated_row.png',
    type: 3,
    target: 4,
    muscles: [2, 3, 4, 5, 9],
  },
  {
    id: 23,
    name: 'スクワット',
    image: '/images/body_weight.png',
    type: 1,
    target: 12,
    muscles: [6, 11, 12, 13, 16],
  },
  {
    id: 24,
    name: 'ダンベルスクワット',
    image: '/images/dumbbell.png',
    type: 2,
    target: 12,
    muscles: [6, 11, 12, 13, 16],
  },
  {
    id: 25,
    name: 'バーベルスクワット',
    image: '/images/power_rack.png',
    type: 2,
    target: 12,
    muscles: [6, 11, 12, 13, 16],
  },
  {
    id: 26,
    name: 'スミススクワット',
    image: '/images/smith_machine.png',
    type: 3,
    target: 12,
    muscles: [6, 11, 12, 13, 16],
  },
  {
    id: 27,
    name: 'デッドリフト',
    image: '/images/power_rack.png',
    type: 2,
    target: 13,
    muscles: [4, 5, 6, 11, 12, 13, 16],
  },
  {
    id: 28,
    name: 'ダンベルデッドリフト',
    image: '/images/dumbbell.png',
    type: 2,
    target: 13,
    muscles: [4, 5, 6, 11, 12, 13, 16],
  },
  {
    id: 29,
    name: 'ハックスクワット',
    image: '/images/hack_squat.png',
    type: 3,
    target: 12,
    muscles: [6, 11, 12, 13, 16],
  },
  {
    id: 30,
    name: 'レッグプレス',
    image: '/images/leg_press.png',
    type: 3,
    target: 12,
    muscles: [6, 11, 12, 13, 16],
  },
  {
    id: 31,
    name: 'レッグエクステンション',
    image: '/images/leg_extension.png',
    type: 3,
    target: 12,
    muscles: [12],
  },
  {
    id: 32,
    name: 'レッグカール',
    image: '/images/leg_curl.png',
    type: 3,
    target: 13,
    muscles: [13],
  },
  {
    id: 33,
    name: 'ヒップアダクター',
    image: '/images/hip_abductor.png',
    type: 3,
    target: 11,
    muscles: [11, 14],
  },
  {
    id: 34,
    name: 'ヒップアダプター',
    image: '/images/hip_adapter.png',
    type: 3,
    target: 11,
    muscles: [11, 15],
  },
  {
    id: 35,
    name: 'ブルガリアンスクワット',
    image: '/images/brench.png',
    type: 2,
    target: 12,
    muscles: [6, 11, 12, 13, 16],
  },
  {
    id: 36,
    name: 'ダンベルショルダープレス',
    image: '/images/dumbbell.png',
    type: 2,
    target: 3,
    muscles: [3, 7, 10],
  },
  {
    id: 37,
    name: 'バーベルショルダープレス',
    image: '/images/power_rack.png',
    type: 2,
    target: 3,
    muscles: [3, 7, 10],
  },
  {
    id: 38,
    name: 'スミスショルダープレス',
    image: '/images/smith_machine.png',
    type: 3,
    target: 3,
    muscles: [3, 7, 10],
  },
  {
    id: 39,
    name: 'ミリタリープレス',
    image: '/images/power_rack.png',
    type: 2,
    target: 3,
    muscles: [3, 7, 10],
  },
  {
    id: 40,
    name: 'ショルダープレス',
    image: '/images/shoulder_press.png',
    type: 3,
    target: 3,
    muscles: [3, 7, 10],
  },
  {
    id: 41,
    name: 'サイドレイズ',
    image: '/images/dumbbell.png',
    type: 2,
    target: 7,
    muscles: [7, 10],
  },
  {
    id: 42,
    name: 'リアレイズ',
    image: '/images/dumbbell.png',
    type: 2,
    target: 3,
    muscles: [3, 10],
  },
  {
    id: 43,
    name: 'リアフライ',
    image: '/images/rear_delt_fly.png',
    type: 3,
    target: 3,
    muscles: [3, 10],
  },
  {
    id: 44,
    name: 'プリチャーカール',
    image: '/images/preacher_curl.png',
    type: 2,
    target: 9,
    muscles: [9],
  },
  {
    id: 45,
    name: 'ダンベルカール',
    image: '/images/dumbbell.png',
    type: 2,
    target: 9,
    muscles: [9],
  },
  {
    id: 46,
    name: 'フレンチプレス',
    image: '/images/brench.png',
    type: 2,
    target: 10,
    muscles: [9, 10],
  },
  {
    id: 47,
    name: 'ダンベルフレンチプレス',
    image: '/images/brench.png',
    type: 2,
    target: 10,
    muscles: [9, 10],
  },
  {
    id: 48,
    name: 'ケーブルプレスダウン',
    image: '/images/cable_machine.png',
    type: 3,
    target: 10,
    muscles: [10],
  },
  {
    id: 49,
    name: 'ケーブルカール',
    image: '/images/cable_machine.png',
    type: 3,
    target: 9,
    muscles: [9],
  },
  {
    id: 50,
    name: 'クランチ',
    image: '/images/body_weight.png',
    type: 1,
    target: 17,
    muscles: [17],
  },
  {
    id: 51,
    name: 'レッグレイズ',
    image: '/images/body_weight.png',
    type: 1,
    target: 17,
    muscles: [17],
  },
  {
    id: 52,
    name: 'アブドミナルクランチ',
    image: '/images/abdominal_crunch.png',
    type: 3,
    target: 17,
    muscles: [17],
  },
  {
    id: 53,
    name: 'ロータリートルソー',
    image: '/images/rotary_torso.png',
    type: 3,
    target: 17,
    muscles: [17],
  },
  {
    id: 54,
    name: 'バックエクステンション',
    image: '/images/back_extension.png',
    type: 2,
    target: 6,
    muscles: [6],
  },
  {
    id: 55,
    name: 'ランニング',
    image: '/images/running_machine.png',
    type: 4,
    target: 12,
    muscles: [12],
  },
  {
    id: 56,
    name: 'エアロバイク',
    image: '/images/ascent_trainer.png',
    type: 4,
    target: 13,
    muscles: [13],
  },
];
